"""order_date not unique

Revision ID: beba960be10b
Revises: 380b2396c83b
Create Date: 2025-05-11 21:05:59.347273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beba960be10b'
down_revision: Union[str, None] = '380b2396c83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_order_date_key', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_order_date_key', 'orders', ['order_date'])
    # ### end Alembic commands ###
